<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings> 
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Imagens\Auditoria_Icon.png" />
    <None Remove="Imagens\Cliente_Icon.png" />
    <None Remove="Imagens\Dashboard_Icon.png" />
    <None Remove="Imagens\Dinheiro_Icon.png" />
    <None Remove="Imagens\Estoque_Icon.png" />
    <None Remove="Imagens\Filtro_Icon.png" />
    <None Remove="Imagens\Funcionarios_Icon.png" />
    <None Remove="Imagens\Settings_Icon.png" />
    <None Remove="Imagens\User_Icon.png" />
    <None Remove="Imagens\Vendas_Icon.png" />
    <None Remove="Imagens\Venda_Icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Imagens\Auditoria_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\Cliente_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\Dinheiro_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\Estoque_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\Filtro_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\Funcionarios_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Supabase" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Imagens\Dashboard_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\Settings_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\User_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\Vendas_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Imagens\Venda_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
