<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings> 
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Midia\Auditoria_Icon.png" />
    <None Remove="Midia\Cliente_Icon.png" />
    <None Remove="Midia\Dashboard_Icon.png" />
    <None Remove="Midia\Dinheiro_Icon.png" />
    <None Remove="Midia\Estoque_Icon.png" />
    <None Remove="Midia\Filtro_Icon.png" />
    <None Remove="Midia\Funcionarios_Icon.png" />
    <None Remove="Midia\Settings_Icon.png" />
    <None Remove="Midia\SplashScreen.mp4" />
    <None Remove="Midia\SplashScreen.wmv" />
    <None Remove="Midia\User_Icon.png" />
    <None Remove="Midia\Vendas_Icon.png" />
    <None Remove="Midia\Venda_Icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Midia\Auditoria_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Midia\Cliente_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Midia\Dinheiro_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Midia\Estoque_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Midia\Filtro_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Midia\Funcionarios_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Supabase" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Midia\Dashboard_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Midia\Settings_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Content Include="Midia\SplashScreen.wmv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Midia\User_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Midia\Vendas_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Midia\Venda_Icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
